config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: %i[get post]
  # Defines the root path route ("/")
  root to: 'users#index'
  resources :foods, only: %i[index show new create destroy]
  resources :recipes, only: %i[index show new create destroy]
  resources :recipe_foods, only: %i[create destroy]
  resources :public_recipes, only: %i[index]
  resources :general_shopping_list, only: %i[index]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can %i[index], Recipe

    can %i[destroy show new create], Recipe, user: user
    can :show, Recipe, public: true

    can %i[add_ingredient destroy_ingredient], Recipe, user:
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :delete_all

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :delete_all

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  def all_ingredients
    # All ingredients that are in the recipe
    RecipeFood.includes([:food]).where(recipe_id: id)
  end

  def available_foods
    # All foods for user that are not in the recipe
    user.foods.where.not(id: all_ingredients.map(&:food_id))
  end

  def total_price
    # Total price of the recipe
    sum = 0
    all_ingredients.each do |i|
      sum += i.food.price * i.quantity
    end

    sum
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food'
  belongs_to :recipe, class_name: 'Recipe'

  validates :food_id, presence: true
  validates :recipe_id, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :foods
  has_many :recipes
  validates :name, presence: true

  def general_list
    # get total quantity of foods required
    foods_quantity_sum = RecipeFood.select(:food_id,
                                           'SUM(quantity) as quantity_sum').group(:food_id).order('quantity_sum')
    list = []

    # select foods for current_user with insufficient quantity
    foods.each do |food|
      expected_quantity = foods_quantity_sum.where(food:).first&.quantity_sum || nil

      next unless expected_quantity
      next unless food.quantity < expected_quantity

      list << {
        food:,
        remaining_quantity: expected_quantity - food.quantity,
        price: (expected_quantity - food.quantity) * food.price
      }
    end
    list
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  private

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      format.html do
        if @food.save
          redirect_to foods_path, notice: 'Food was successfully created'
        else
          render :new, status: 'Food was not successfully created'
        end
      end
    end
  end

  def destroy
    food = Food.find(params[:id])
    if food.destroy
      flash[:success] = 'Food was successfully deleted'
    else
      flash[:error] = 'Food was not successfully deleted'
    end

    redirect_to foods_path
  end

  private

  def food_params
    params.require(:new_food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @general_list = current_user.general_list
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes([:user]).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    recipe_food = RecipeFood.new(recipe_food_params)

    if recipe_food.save
      flash[:notice] = 'Food was successfull created'
    else
      flash[:status] = 'Food was not successfully created'
    end

    redirect_to recipe_path(recipe_food_params['recipe_id'])
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])

    if recipe_food.destroy
      flash[:success] = 'Ingredient was successfully deleted'
    else
      flash[:error] = 'Ingredient was not successfully deleted'
    end

    redirect_to recipe_path(recipe_food.recipe)
  end

  private

  def recipe_food_params
    params.require(:new_recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.new(recipe_params)
    recipe.user = current_user

    if recipe.save
      redirect_to recipe, notice: 'Recipe was successfully created.'
    else
      redirect_to new_recipe_path, notice: 'Recipe was not successfully created.'
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    if recipe.destroy
      redirect_to recipes_path
      flash[:success] = 'Recipe was deleted Successfully'
    else
      redirect_to recipe
      flash[:error] = 'Recipe was not deleted successfully'
    end
  end

  private

  def recipe_params
    params.require(:new_recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<section class="grid__container">
  <h2>Add Food</h2>
  <div class="add_food">
  <%= form_with model: @food, method: :post, scope: :new_food do |f| %>
    <div class="field">
      <%= f.text_field :name, placeholder: "Name", class: 'txt_input' %>
    </div>
    <div class="field">
      <%= f.number_field :price, placeholder: "Price", class: 'txt_input' %>
    </div>
    <div class="field">
      <%= f.number_field :quantity, placeholder: "Quantity", class: 'txt_input'  %>
    </div>
    <div class="field">
      <%= f.text_field :measurement_unit, placeholder: "Measurement Unit", class: 'txt_input'  %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', class: 'bttn_success' %>
    </div>
   <% end %>
  </div>
</section>

app/views/foods/_table.html.erb
<table class="table table-hover table-active">
  <thead>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td>$<%= food.price %></td>
        <td><%= link_to 'Delete', food_path(food), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn bg-danger text-light fw-bold' %></td>
      <tr>
    <% end %>
  </tbody>
</table>

app/views/foods/index.html.erb
<section class="grid__container">
  <%= link_to new_food_path do %>
    <button class="btn btn-primary p-2 border-0 text-light fw-bold my-2">Add Food</button>
  <% end %>

  <%= render 'table' %>
</section>

app/views/foods/new.html.erb
<section class="devise__grid_container">
  <%= render 'form' %>
</section>

app/views/general_shopping_list/_table.html.erb
<table class='table table-striped table-active mt-lg-4'>
    <thead>
        <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <% @general_list.each do |ingredient| %>
        <tr>
            <td><%= ingredient[:food].name %></td>
            <td><%= pluralize( ingredient[:remaining_quantity],  ingredient[:food].measurement_unit) %></td>
            <td>$<%= ingredient[:price] %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/general_shopping_list/index.html.erb
<section class="grid__container">
    <h1 class='text-center fw-bold'>Shopping List</h1>
    <hr />
    <div class ='d-flex justify-content-between'>
        <span class='fw-bold'>Amount of food items to buy: <%= @general_list.count %></span>
        <span class='fw-bold'>Total value of food needed: $<%= @general_list.reduce(0) { |t, i| t + i[:price] } %></span>
    </div>
    <%= render 'table' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1 class="text-center">Public Recipes </h1>
<hr />
<main class="public_recipes d-flex flex-column gap-3">
  <% @public_recipes.each do |recipe| %>
    <article class="card d-flex shadow-sm">
      <%= link_to recipe do %>
      <section class="row p-3 text-dark">
        <header class="col">
          <h3 class="mb-4"><%= recipe.name %></h3>
          <h5>By <%= recipe.user.name %></h5>
        </header>
        <div class="col">
          <div><b>Total food items:</b> <%= recipe.all_ingredients.count %> </div>
          <div><b>Total price:</b> $<%= recipe.total_price %> </div>
        </div>
      </section>
      <% end %>
    </article>
<% end %>
</main>

app/views/recipes/_form.html.erb
<section class="grid__container">
  <%= form_with model: @recipe, method: :post, scope: :new_recipe do |f| %>
    <h2>Add Recipe</h2>
    <div class="add_recipe">
    <div>
      <%= f.text_field :name, placeholder: "Name", class: 'txt_input' %>
    </div>
    <div>
      <%= f.text_area :description, placeholder: "Description", class: 'txt_input' %>
    </div>
    <div>
      <%= f.text_field :preparation_time, placeholder: "Preparation time [HH:MM:SS]", class: 'txt_input' %>
    </div>
    <div>
      <%= f.text_field :cooking_time, placeholder: "Cooking time", class: 'txt_input'%>
    </div>
    <div>
      <span>Is this recipe public?</span>
      <div>
        <%= f.label :public, 'Yes' %>
        <%= f.radio_button :public, true %>
      </div>
      <div>
        <%= f.label :public, 'No' %>
        <%= f.radio_button :public, false %>
      </div>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'bttn_success' %>
  </div>
  <% end %>
</section>

app/views/recipes/_modal.html.erb
<div class="modal fade" id="add-ingredient-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Available foods</h5>
      </div>
      <ul class="modal-body list-group">
        <% @recipe.available_foods.each do |food| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span><%= food.name %></span>
            <%= form_with model: @recipe_food, method: :post, scope: :new_recipe_food do |f| %>
              <%= f.number_field :quantity, placeholder: "Quantity (#{food.measurement_unit})" %>
              <%= f.number_field :food_id, value: food.id, hidden: true %>
              <%= f.number_field :recipe_id, value: @recipe.id, hidden: true %>
              <%= f.submit 'Add ingredient' %>
            <% end %>
          </li>
        <% end %>
        <% if @recipe.available_foods.empty? %>
          <li class="list-group-item">No ingredients available</li>
        <% end %>
      </ul>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_table.html.erb
<table class="table table-striped table-active">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.all_ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.food.name %></td>
        <td><%= pluralize(ingredient.quantity, ingredient.food.measurement_unit) %></td>
        <td>$<%= ingredient.food.price * (ingredient.quantity) %></td>
        <td>
           <% if can? :destroy_ingredient, @recipe %>
            <%= link_to 'Remove', recipe_food_path(ingredient),
              data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
              class: 'btn bg-danger text-light fw-bold' %>
            <% else %>
              <span class="text-secondary">...</span>
            <% end %>
        </td>
      <tr>
    <% end %>
    </tbody>
  </table>

app/views/recipes/index.html.erb
<section class="grid__container">
  <ul class='d-flex flex-column gap-3 p-0'>
  <%= link_to 'Create Recipe', new_recipe_path, class: 'btn btn-primary' %>
    <% @recipes.each do |recipe| %>
      <li class="card p-3 d-flex gap-3">
        <div class="row">
          <div class="col">
          <h3 class="mb-4"><%= recipe.name %></h3>
          <%= link_to 'REMOVE', recipe, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          <%= link_to 'VIEW', recipe, class: 'btn btn-primary' %>
        </div>
        <div class="col"><%= recipe.description %></div>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/recipes/new.html.erb
<section class="devise__grid_container">
  <%= render 'form' %>
</section>

app/views/recipes/show.html.erb
<section class="grid__container">
  <h3 class="text-center"><%= @recipe.name %></h3> 
  <article class="d-flex flex-column gap-3">
    <div class="d-flex justify-content-between">
      <p>
        <b>Preparation time:</b> 
        <%= pluralize(@recipe.preparation_time.strftime('%H'), 'hr') %>: 
        <%= pluralize(@recipe.preparation_time.strftime('%M'), 'min') %>: 
        <%= pluralize(@recipe.preparation_time.strftime('%S'), 'sec') %>
      </p>
      <p><b>Public:</b> <%= @recipe.public %></p>
    </div>
    <div>
      <b>Cooking time:</b> 
      <%= pluralize(@recipe.cooking_time.strftime('%H'), 'hr') %>: 
      <%= pluralize(@recipe.cooking_time.strftime('%M'), 'min') %>:
      <%= pluralize(@recipe.cooking_time.strftime('%S'),'sec') %>
    </div>
  <p><%= @recipe.description %></p>
  </article>
  <div class="buttons d-flex justify-content-between">
    <button class="btn btn-primary fw-bold">Generate Shopping List</button>
    <% if can? :add_ingredient, @recipe %>
      <button id="add-ingredient" data-toggle="modal" data-target="#add-ingredient-modal" class="btn btn-success fw-bold">Add Ingredient</button>
    <% end %>
  </div>
  <hr>
  <%= render 'table' %>
  <%= render 'modal' %>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand logo" href="#">RecipeApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <p class="message">Logged in as <strong><%= current_user.email %></strong></p>
          <li class="nav-item nav_ul"><%= link_to 'Recipes', recipes_path, class: 'nav_li' %></li>
          <li class="nav-item nav_ul"><%= link_to 'Foods', foods_path, class: 'nav_li' %></li>
          <li class="nav-item nav_ul"><%= link_to 'Public Recipes', public_recipes_path, class: 'nav_li' %></li>
          <li class="nav-item nav_ul"><%= link_to 'Shopping list', general_shopping_list_index_path, class: 'nav_li' %></li>
          <li class="nav-item nav_ul">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav_li' %>
          </li>
        <% else %>
          <li class="nav-item nav_ul">
            <%= link_to 'Register', new_user_registration_path, class: 'nav_li' %>
          </li>
          <li class="nav-item nav_ul">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav_li' %>
          </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<section class="grid__container">
  <h2>List of all users</h2>
  <hr>
  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="bg-primary rounded p-4 item shadow-sm list-group-item user-list">
        <%=  user.name   %>
      </li>
    <% end %>
  </ul>
</section>


